language: java
sudo: false
jdk:
- oraclejdk8
notifications:
  slack:
    rooms:
    - gtas:G1lDbK5rR8cNBEhlszZNGDnL#general
    on_success: change
    on_failure: always
  email:
    recipients:
    - david.j.ertel@cbp.dhs.gov
    - maneesh.lekkala@gmail.com
    - taylorjwdev@gmail.com
    - jtangfed@gmail.com
    - vempatisvr@gmail.com
    - mikecope@gmail.com
    on_success: change
    on_failure: always
before_script:
- cd gtas-parent
- sed -i 's/admin/'"$DB_PASS"'/' gtas-commons/src/main/resources/hibernate.properties
- sed -i 's/localhost/'"$DB_HOST"'/' gtas-commons/src/main/resources/hibernate.properties
- sed -i 's%message.dir.origin=.*$%message.dir.origin=/usr/share/gtas/in%' gtas-job-scheduler-war/src/main/resources/jobScheduler.properties
- sed -i 's%message.dir.processed=.*$%message.dir.processed=/usr/share/gtas/out%'
  gtas-job-scheduler-war/src/main/resources/jobScheduler.properties
script: mvn clean package
after_success:
- cd ..
- chmod 600 deploy_key
- mv deploy_key ~/.ssh/id_rsa
- scp gtas-parent/gtas-webapp/target/gtas.war gtas-parent/gtas-job-scheduler-war/target/gtas-job-scheduler.war
  $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
env:
  global:
  - secure: pci+ZSmv6cOwB/uZN8sZKV5BGdNwCqGdKRPsRrdbQpsGEncLfYOe8I5TVVHwKKKe2kiUwCTKt3rqrdsbcQjkc4N7ud2ko+j5D218DjAyW5XLuQ0fMljGZEwJSutYkCt8rjZjvQfBnyAOODu4aybMsjJzGNWAieFAKFj7U1wr+OTNuXmNxTojbwM08CvHfdiBCsjehh0uQ1Z19LJERs0NjxmXtxu2kHmZxqzvDg7aPmJNSG0JMQMsdUbeJiHeCbv9Bq+1y02vrEvLhMhAe0MdKxBwynEQAGdK/x6xKimkYK+pr6kFCXrVbo6W589YXlbdqhgzCBTY6XcOuth7klo9iB28PrFdx8un0/BZGzEwdwlontNrOlvIfTjoB3ZYDgEcKMbHnwG+yXQm02yRKsfiJu+tH2le04Y708zs/LzXLlYluKS+syzhKsQT+1BYxiahlq5AdloL2DypGoFKDUmR/38nNaqP+T4Dhw+PKDcq6z1/dmdz5KJVbpvIOVxsKyom7u5d+X1zFpH4Ng+j78nuSzKVtHqVfWKLLj87ARF/rplhoKZvleTUXY8AbNsYzCxREQXgNgHP0Q1AbOTw0NsTSo4KLQ5bFsD9+h1+u+O0vEP7cWr+5xk0NYbV41pjbUm8dF4zoMnrfaiwX3T1pENOJ81el3eWCXnGJij+e2426is=
  - secure: BoEO3v10jILTaDTmWNGzAAW+qhW09Htmi7ivIzTqKrUZ69dYr1vt7QSOhwpfNx4DAuAIDoTL1+VD/B0tLRMhLTZ+rz2BpXdX6JDeWOBjoGgu3jqoZ+eh+EgOAXOwozw6IjKJadElm/EnQQ07RHuLNIux8lk2BMUFsy7xLbOXhXxWc9xx3+Ne5MlPOiv5nKgUAzR/F8VnqT8TSBe9hT4jCmj8sviI4fxXSut/QvM0MxnhI6bZgEVd7CVgW9eflq2b18OS+bKOhm+3fLuQ4ORNYtVAl64VAPohnwbbJi/i48ZmEacCSGyrsagbZZST+HS6NYUE8ibmjSiFmJbZcFGzvjyBiW/6q25u0aCkLhsKZ4mrKe5kFdgfcaHzftzA1xXdCBKuFAlf41L4ImPqCF/tLtK1U65oaZhKc0btnAD8qkxlOofZWKVUIoaSIEeMd3QJxnfCnzm6ErSqDD0vAd26bvjXRRyLtvqaJftBtgKM9W4uYJ2i6QHLdcrpNjoexcqy1IGw8puOY1ZrqHeurPE9WKijdUczSPYQTcv3y+m9bXY809tihe7J/GUJYMMYc0EqTirVuA5mKFYBTVgZ1dXavwA6UduhybOHCh1gnh22Z8FKJKy+q07Tas/QTNvyLbKE77pB5VIVyz8S/v+yibpnVeVMFvVryWgL607Mf3YMV74=
  - secure: opTZR1c7AEmsvbkuCPlr3xvpC1RBp/0bFSyqVWG4beHd7xY+wTR8G6Dr8aQRrDb2abaF+KSHUXVNRIvQ6IfjSK1JLwRc+R3MnMwySiCPatoXRApOCRmZtcj0VFqlruItT22Th+iz+gH5VHoK4Om1y2GxU26+nnSCBLfWmALZnJbX5tSPd16lzWfqcHA0FRD1DXh2RUL8cj4YxLjgwaYmL5schDKLL+SDpEe0pIYl9XhfIfjHx1Zbm6lveoiPGZmZibjgQZuCrG8iqE6P1sAnSWb6GnD1V10h8l218d3h7MIfrmAd1DAQf3zOnltJezgTjU/sBM0F3EJ9CkfxEJWHn0x3ngdmwEiD8GhdU7yeddiKDcRAyW3J//QTU0+555tF3BaaakUWvBBRKbXzkNOTPFaWGFBSXYE91cs4c1ay7hmkmqiVPEEiwbJSG4lGBkhcCnhOQ6SSJKp1BXJedIDndQAgvtIJtXzknPACrbk/ugyh82ndqqChrm1suKE5IF7l+JtJbYMojwzsWdhRXMxzUaoxjGfWR8/4ejbXjmeeAJOD0Vr3ArQdVlP2Qv24o+JgBdiGk/QBCgSX8NZWcXyOV6X5mvg3ywL46zFF5had9sh/MdvisJzjmp6vo9YESr205wbuqF9GFpsN0u+22yX792SUqqRV+wkTjCs1k+l+6BE=
  - secure: n9X6m4pfyaJfmx1ASe4Kxpea/21ATpSbALGemW+mHbztahXpW2pO7AzsnTyNT1FOKCM1gfPD0QgLPdTb41JifWMisMmIVwEy+0phSyFXgXATOFZuigLN+5ZcK/kG7LFpplTkHIAd08CeNJ2osPrpfpmpSFfzOA2VXixgI7AI1U9jfvgrBiaQGNuADnh3YarzmyUnDUlwbo4GBQ03La+nr9+c9hp4YkPiQOsRXEMHIZ+AWloIsVj7LCaT79yAJkWVimVL7vhvQD0wHu4BgdKoXh924jPpmKGMHH+FktIBVepNcUDT5Xn3zWSK6S7hvGYFQfoCNRakHCw6vh1BqTeP1OHTrPfsCo5Q+8ynmWGtcoSNjzG4rnLV68b68KXyiZ1BhG5gZnH2ZBiknXsfJAmqyuxSb6Gc+jiJXGTvvP0Ulx4Z8Cj0OQhH4rP42t9wKfQIbG9SNsti0i+HVQJ+XTSZa0rL5P49odYYhod5YDANeGr9hDgQa9oE9PX32AnO0EcqUP3WqaaICc3+PeR/fnYreyUVYgKPEPxsb2+1OA6pFfXf9/3sgsxXe5HsxjHbiMCBH4JBmM8bRWaiALMHmzaTL+5X8iBRYciWXSDLiE55hh7n5UxglD+dsInfaihSwggmjQHsuwAPj70+1A+qUYkhzYsgVA7v538GK+/iTyLCLFk=
  - secure: g2oGrYft6+PNj+5ETjUg4MOagCLRKl6x75q0ZEKraS95v7F/TPl/Rj/HkTBJ+vApbOy0DNN+Zquwq8UY6DhD4TW5jMcnO74rHz1yFbB88XGmYkEYp+MgsB8odx1iI6nsj7NQQw+WWRG+I04dMEzSZV9J8VPtC7AI0ISK0gckp2poGCfh78qI+CM3sNDCjf2176rRZlXyBjSEuJf0C6bpvWKL3ojNaA5dtuSr5pQTZGk04l1sJNp4meWFafAsZE7dqOCk7Ng9REFA3VdFhoeWvrc7aBE85lSDz1dNpNyN36S/Ov9inGhpSNf5zaepEYZcjgEM1FmDzk3V+zFTErXpuSf6lvCxeI3P8eVUbTi7a16a6idSaLfMILWyA/Q7rfmYld73KjmvVsb3JyHWC9/vdgTm3Do25ZbNi1sqsX+QBcwHb/F3n8bTm1sZCgiZAMiUvYo7GKf5+3RphvW02T+oDrePKKYFV2Fis/5b5oWowSG+wVvuKC4EkLMhcEsYtJ0Y7SkIxCPW9i+2j08r9mN8S0Dg543Aevzc8msvrNLkLbkhjGAasd5KJFaT3MTFL4/m8SikIEPnmDh10tmSAXFydczxcgZQLez88woedNuaY8R5gfJRx8aHeRVByqJq5+TY3wY4cbkq7Rdm0s5QR2ujEJCy5cj2EVF/6HBjplwA3KE=
before_install:
- if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]] ; then openssl
  aes-256-cbc -K $encrypted_ea9b11edcea7_key -iv $encrypted_ea9b11edcea7_iv -in deploy_key.enc
  -out deploy_key -d; fi
- echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
