language: java
sudo: false
jdk:
- oraclejdk8
notifications:
  slack:
    rooms:
    - gtas:G1lDbK5rR8cNBEhlszZNGDnL#general
    on_success: change
    on_failure: change
  email:
    recipients:
    - david.j.ertel@cbp.dhs.gov
    - taylorjwdev@gmail.com
    - teddygtaswork@gmail.com
    - tsegay.tekle@gmail.com
    on_success: change
    on_failure: change
before_script:
- cd gtas-parent
- sed -i 's/admin/'"$DB_PASS"'/' gtas-commons/src/main/resources/hibernate.properties
- sed -i 's/localhost/'"$DB_HOST"'/' gtas-commons/src/main/resources/hibernate.properties
- sed -i 's%message.dir.origin=.*$%message.dir.origin=/usr/share/gtas/in%' gtas-job-scheduler-war/src/main/resources/jobScheduler.properties
- sed -i 's%message.dir.processed=.*$%message.dir.processed=/usr/share/gtas/out%'
  gtas-job-scheduler-war/src/main/resources/jobScheduler.properties
script: mvn clean package
after_success:
- cd ..
- chmod 600 deploy_key
- mv deploy_key ~/.ssh/id_rsa
- scp gtas-parent/gtas-webapp/target/gtas.war gtas-parent/gtas-job-scheduler-war/target/gtas-job-scheduler.war
  $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
env:
  global:
  - secure: WTu3aWkJ+yfEuPN7nLcMeY89NY5C52FS8CagrxFfstNF3cVz2nEDOtyfCJ7iKqRTTKSokMlDtjx7vIS+HLzJfiNggiZelz2BUlkp5jnwmlyhorvCQgS0mYppo0bN3mvvBgPXi1JRSiIaElFS54la6X9j5C4eIfZqpqMdelwuGU+OO+nBitl28pjWFs1PeXuXrqC4PTJxL1+nvrirWBdhm/dKBm/R+tl3iy2fQtLb8wZQP7PifID8VOBliwcdi4+aKRCsrbdI4qtByUj3Wke/pwwbEkfhjTpo6QeLiUWRtMrISqA2ekzm0eJN8L6+gR0bS5Rv88NmAQMwQShmoxysI/1qvMAoaif5afyA3IfA/onjYoVyZdQpfClvtsjUZrcRtbSu9GEZPx6ururBDblS1PnP1+692pTIYerFj0Kn5WGKeUIvzpLx1S/WztNkGr6KONcJd6gIlw3054uAIidg6razZcvZVCJ4wGXOO6Hz24oWoVZJZ/MLtfWGJ1RUsn1edN8pF+XFjZjH1V05m6q/uLt+lHc8cAzXTwUrR0MnE8Y7yC95DyA/N9LYFVPFac1YLWmYU2D1Da7BZ/ImbEzjqdNLfiGs+H61BeoFE0ct+veWtS22f/Zh43Fq+gyEnREqi/srOFPv5SLgLZNU6H1+jKpyazVyRWzFYgdxnpfAQ44=
  - secure: A+64wp24Qb6dGC1Q1pMshMORikEX/2dvRNe87FC+eSvSNNtu4qlH18Ihus3J+1aRdFQgC2dH9cYQigrzy7u4Yg3P61SCMV1zxg/pzoeu26iJf6MobDHDH9FJakrYlLfNqJ+v9wYO2EhqbneRkxDuyyB+3ECkvQGpY6fd3ay661Wx8BphOuj/PX/gzNs/ENGYlr6tm09XnQWi0jp369NO5uR7w19TSEid9eUcDw1pXqCguuDK+xhYHFj2ZX/24LMoW5Mt0esTmvqvksdD/k8qZmq2M4sBBfzKRhiycb9Gih1l6IYeBdEFA4Q0HjUzUtNP53+7rIo7DfFlU9WGNBLgkRQcX3JAZFlu3W2bMccqbyzPnBLZm/SBMmKZrXOlWtgIy+l0K7RCeaeGbS30ZDASS7V8wxTG++CRCGQrt4oBOusCiQzXCaH3t9dPIBJfVaMTlJJUURQIcp4m4QP0yqtm4Vkshy+8Eru8q9GX9FjF6iY/fgRpFtCTZU6xvHmroTCrPaQXgnZPxaMWk3C+in6x1AESolbAu5OPupZSSvESikyRLOSGHuqD5UpMNPALSbbAGxoWc8qMQsVc9QZe6q+Ehcp6QuMeoMtPQSv+MY9//4vU4Cnj8B6nmpwIU0sspIpML+CdpH7Qg/Gy5pVwt9f5n8LvJ2ytQEAt0v8E2HTnS28=
  - secure: bE5QkvD7FMBFbBFhcl9CgYe59t4KA8YuAF5r1dhqTE2g/SGzkuM+Tvz7BpWglkw9WdYmoQIdemxtH/+0ukqB+2yFH4hvJgquSjYVGt4cha5Hs1Lzv5kGpy2JBYvj7a4NQc4vjeGGlteiRsVj68Kyd/f8aoJNI7lTPr1GpThZQ9yTXRQbs8oYa6QW16cN3aNwTdSJfHk3WP4Ki0Eq7Af/tb0hxZ0DK9jh+/IwDJsIr+Z2INf1FcU6dlnRZq4BO5mz3D/B7v+eIFa6Ncc4drE1c6ExVPFI3bHuylRh1LxITtXNUhBmuOj1Nf/NG32zto+ga32WgTDaLYQHjsCgM3PlYV2MMBeSjb/8+yRBzG1LWN7Y7j/Ay29ivtSjpoYtgV7FujtdhKVdgTuZgYCgVubW9EU4KXytQkHAY6783shK3DlTP1Pjs0INvnLePt4RRRHBTeG91creK8pcTNvcXdydshwOWYgZ+akNDGVJUwAFSaozKizLeF3bbVDA4hebR6cpha0ybmxs7VVWO+71eNnAT14hncaadxwBoTei/VJ1CsJPli4/7GcXKAi/MNoSGjT92C9VWUC0onHDdAhLbPz03T4wt8Dw/5qq1oCGpRDSWEzQnrz8IV7QUqVp5QJS+vJMj4sPpBtD6lYWEqBgDAk3uccWJT/sLNthhM6AegdUISw=
  - secure: BzdBubovVHOpsx3utqTPq6g4+fMganNvU2hkR2k2HTI+mwZ4s0GwFEa4sYQy1rkTSm90tSLLSxeQbeSYXAY668TxFFA5UzHlGdMyqLPCoSVt1EgI4lOWCSW8B9wqVWH8dXyos+E8tfKQUTrBGee22aMvkQk6Mhg8EwLR0yv9a4ZEBr1HyPIKjI6j9ek+0nS6Sw5IesXw44V2lS7DKT8gTQO7TjSyI5jyoDUBjRwavE/eyr/1cbBGevx1Ug8SLBe6eo8742ckUu8Mu8c0kuLOkEAkETDZaZHHTtwVHJ2O1YroJrMVCotN0hPSftUH6p6eA7VdHuNjf7HoVKvphNwP+16TlRMCZIKwozQy3L5Xl2wn4zrYlaGGD18HbCiBPm/AT8J2Erzn55e6bQatHT/JuXyZZDDSvjJE7v10ckB1HTviWFyWcdAEgnGrI20Bu5SpQOgPPA4w/DuYHco2taemdvFXW2sVCGQYFHAlat+lEOgJQB0wI5VOxr71OqJZFVu5v5gjGnX/g+brGA8vMrsKNVliE6pPYUUtj3HpjUYETZNdUbMx01HDmOqkhc0TsmeOE4jq/fjVqKB+uw8oeFAwQVejw/ecP/gXA0vb1Qr9zv/seABCwvTcNnW31V4HpgtnQYvXY2jGjUqCcsEI5GbyihO+Hlw6pd7WIa8J3o6FH0E=
  - secure: CgnYvMULP3erFmPPSBr83Bh12SIxsop1F/boXxa4zinaI5W1PW64eqKsB3MFSFDxfORnnAYdpLNHO9sabMxwMTwkofTRrIkXu87Bd8Ys1zrkU369VtbXaGfN8TxOneNQtwdmRB0qKV1EJyIH0GLx2nQSHb9v8Y1YeWYBCkKagEGQgQfFaWW2ULN2GPpYvuySG0W/3SsR+hbOwa2ss/6BK8CRsjdqNVc3vYNcuTKRLSqu6HnHSjv99XXC3jne/L7MGaQg0+T8T8DuIJOdSdhkrq9nsYmGvINbDlpM6RkTBTM1u92Yz9JLj7wdkiHwroQD1qFXpO7A72qYMiH1VW37rb87Cs8xwWcwSX9MQp2W5VvIIEL89+UQnAmtcsNoJLyx1wrzijq05FzlaQel50/Tg4L1dZIe/HL38Qy3FdCORyvYBa1sUEer7xmx/eagEggtLgTpOF7MCsTMEUbz1HOrUAa/rBQuM374I27SPYOrfo/REvjP4BMY6v/vV15yVpMo6E/GXLOSMOvfkVE2d7i+IAdHeyWitd5nAht0+Z/NsdNV639uuIhr+eUveqirCM7V0iRodfi/F+W6HXkOOrhIlGT2MNqQcUUxBfOn1tTST6UqRW9CjV6RQo1UJ36gXHnvAiscD2rHs9upSqm1APfSwY/uoH0ywzVzr6ZM1kaWmEU=
before_install:
- if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]] ; then openssl
  aes-256-cbc -K $encrypted_ea9b11edcea7_key -iv $encrypted_ea9b11edcea7_iv -in deploy_key.enc
  -out deploy_key -d; fi
- echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
