language: java
sudo: false
jdk:
- oraclejdk8
notifications:
  slack:
    rooms:
    - gtas:G1lDbK5rR8cNBEhlszZNGDnL#general
    on_success: change
    on_failure: always
  email:
    recipients:
    - david.j.ertel@cbp.dhs.gov
    - maneesh.lekkala@gmail.com
    - taylorjwdev@gmail.com
    - jtangfed@gmail.com
    - vempatisvr@gmail.com
    - mikecope@gmail.com
    on_success: change
    on_failure: always
before_script:
- cd gtas-parent
- sed -i 's/admin/'"$DB_PASS"'/' gtas-commons/src/main/resources/hibernate.properties
- sed -i 's/localhost/'"$DB_HOST"'/' gtas-commons/src/main/resources/hibernate.properties
- sed -i 's%message.dir.origin=.*$%message.dir.origin=/usr/share/gtas/in%' gtas-job-scheduler-war/src/main/resources/jobScheduler.properties
- sed -i 's%message.dir.processed=.*$%message.dir.processed=/usr/share/gtas/out%'
  gtas-job-scheduler-war/src/main/resources/jobScheduler.properties
script: mvn clean package
after_success:
- cd ..
- chmod 600 deploy_key
- mv deploy_key ~/.ssh/id_rsa
- scp -F ~/sshconfig gtas-parent/gtas-webapp/target/gtas.war gtas-parent/gtas-job-scheduler-war/target/gtas-job-scheduler.war
  $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
env:
  global:
  - secure: WJnZ4Cud6sG9sbomHWOONCA15wBqULdYS1jX1nlEs02zpcvuCiM66zDS487zgQtf7GjFefcOVnVNCIhLiCgOCZo3+XJEwC7upFtXAlNLFu9qhM+o6MCzPffBnp+b69jpmZ85kBE9ity+PIeAzZpW4slzlyvqvEKMRkxYuFanMiTm18n0am+zL8I0VwvnmfjyR/9fMi6ukdNuqWdnu2PIQY6y9wONUp9CTPyDLdS3aBTDU+ojfTygM2QU75BoyipJxsaSzGcIgiKaAglpeU9gBcndi3puaifxepiEqSuc4QjgR0cCfQKKpWfIjpraU2tWecqNyV6gikN52S6OuiJroM/J+quykrWYwNXgG+E3Ls44CilE48aev6fosyOaHSnwIdqhpCbL4B9pq7ALsDfQ5IKGz4cRFNbZtsN5nScTcRDQWsL3DflMWOfWo0M6WZ2efYAwcxDkKhFJkHwmt7TNwNWxV841ynWG+7VvTcA41+2T93Cu7bSOGy619R0FpouN+2eo1G7PkywemeK5RlPLURHFD13nJ7CLVR9C9/71H+/jwOoBB3FxGU1HWfb6lNUP8TlkBzWgyCaBEDvmeEh49a4xb29xxPW5NXJkandx2EP+26T+Pc2hrbALlQPSbam2tI/UyDWSl16mTKXauIGP2d2sniX6OesnCFEJF7DHCzE=
  - secure: OmMCJ6390t+qd0yv7BILof9TLMf8+OaPvSmdhRJ7r7Whrq79nSgHL7BAXZpSDQBYvj6ob2lH/vMxhl2vpitl4RhFt+KjAFn+bIDhzD4gUpZn82klVdRFH1KIYwcHJeyxb17+YpZmsnej4kMfZ4BCooYjtGs0BTCkqqwJExwbYIyoDgVnVrIDQ5zsvHvopiBQa0n0219Bx5wd0qoX7hmW/8bLTd0xLN8iNLiKZ3qlTrcgkzM/WU9vILrXguVrVIwCt11+oEC0+Uq9vxRFJ4ItFb2ezLNABfRVW8NhEYkIX0UHaed05auOP+GonLtaF3rAPNQyTe2humYYzX44MD03WeuVwroOx+G3bZymiJYbY9LXz7z2dkPl3kySFIdsyrRglwCyusjk/motjdNql6dfJXNrC5YaCTUYqslcWnokeJ+XS4cYVCzyVQsmaCCLe5IDUmndWiloKBUcB4ip3clLfAPvdaUWAqtemKF3q7UuIrTFoJPQt77zOgEfqnFQnubeLWaRwhEvhr5oQIQROxQDZCUTZtPRA+7zDvxXVNVjVVCe8gVk8nCfbjsWuMSrPAZOg0Qk4E4D1V//e+iWgem4cmTxrghu/PdvWHpTrd9eVBucNJxa6XsmVakfqFkvhffPJVSpMCpTTVpVKGGAqwmp5/1h96OhKGan52CgaVoPUSI=
  - secure: bx46eWx0LGTB8p9c+7SBcFxiw5UcLi0N0ja3719LBMgOD6WV9gHzm1WVYUrMJyQFFJhWrzunig2jc7R3JS5q2mXzXAcU4Q1/2XMh+nz/FfhHO8A2MYEPPeht0CF9tYfPGTyshwL3Wf7hdC6fduucUQjcwkaNGid1+75rUgGfGzL4WgadvTdz1s5stYdBZtYLQVzdKlt4+cxMUjz0T82NUOeZspvmej/84+fUfVXAjunBxfLGeGsNMFgVA01ZAvWnN6lLbiO8B2MnYdPK8wbiEWns3+VOYPdBCvtQQ67Q6EoIFU823yU1R0yVbkRdylNx/8zwM+owtcEsziUDcvgIln0aej8yGE3S0oZ/oOMYKDkFHlFChaMFtStGJHgKt4rV/pQmOdqxSCW0Ub+CaG1YpNK6UB6r2XVXJ/ruF35GrTUMjBovShCkNuUZ3J90w/7y9G9Bz3H/rnqfIIf+0SJysNApRze7093S7bhC59xdXyzdQOiDvCwFTPHkY2CSwTxmuP07EGg8OLhEfarv6D5otLsMZGnPwg2F+kJjVcOLaPq0KmyDFYBfd3c1ca0tIsJlJjLMT3TlBSAHJxfeTesdfjXzpreHMorlkrgL0tii9FO3ze/u+3C+pgAe+b1ObJ07ElmOMVsbzTXfg/pqkG/ZtpWVFpznivxM++vKyobOiDU=
  - secure: Jb4fEUCNe44HZlBg+VdVB2G1I95SmKtpRxxXep3IF0BpCXd2rioxBEIkf6xlL+/7M0h7f6ynEcDME0bNha3lsVUoPZzhBM5FvOyNBm4CMb+tgJ1YTkjpXHKh6ru57PUtYu+tpTALYpyUEbYV4sW4kkR3WEjiu+irzfKFAFAtfbB5Rs+E9rh8TPBPQMwnSMwnGmEa84mL4WNV/TwFWwKplUyhVhOYrEZQvSiLzD5rKPqUwAY2BRMY7nwYCMYSK6wslNLiJQ/A7TcNbSh+0kFObe7QTDfiQdjqH4eg8ON+RL4N9CeuDATnhYhf9ktzwf8q1JkWEaQrAReYpooK4h8x0kE9VFFtyVqzIZQ3zQepd/brDKoKK18SI6A2PLKhYPcD2Mgo2VGqLOzF7Df+SdHILlgTqmJyQFBd/ocyplHIyVqVV35ro2Zb1Zk04XNdlG3Ax7X8gM6e/7FpxDoyaR/5jMeBMauTZewkFQGXfiWShi625R0vsdp5IDH8dhWJ5m8XZbbMwXPM6IhjKaflXNkz+QaDzX6w1cXQpSxNspx/59F39dDqogjYWRSiKU6QGDmAqaKjRJBIQfV9YIpp9PxpwV/CNJOZmxJyw0Cfs5eS00SN3eYvVowbY239pU00IiIjHSZ8i/OO5T89w5kMgkdMeIP/KTJjPBT10e7RXBcloEY=
  - secure: paFUsN19jT9lgES/sbGqdn3F7SwmPQDh7Inbd0a20xHd63mAIUrzrx7HQsFd965RqgDAWc76ESFz7xJ7ESZW91HV5WXVhDoFU34GlfoklEiWM1WVJz8OLl90y4ZKpi6XVftNDT9BjeG84g5gipGxQGmstbkv9h2ZMBI2jXEvRf8ZCBNblnE/8oZxvmizoeO6/MmD36Yqy3H/gDakMtmoXAqixSyURp2iO+DKJgPD4YtwZ5X8FcDlinHiRW0BBb1LNyPRupm3oYRpgXWbL/yZM91docXZ2NxDLk3QDufBD1p7fsKAVjUYIDervDjKN/TRCaQRosFugUkdwGmF1lgpSXg4WeB6OCTEw0/WLQhd05CRsq24bZ+SMPZrnYvzT3QY30+RUf9XOiyRk2zvQrKnCBMkQSKzAp7TnjNkyEWLuIe6JbHybn62C+K9jhJn5/z+IFwtxDP1XL/LvhXa+H5/zNUnMFgvLfzlcH4tF2eiko+1qGb1YaVAqDgU0todVpnuNQBsUyip9TjcV8tFdfiTSbm6+9kCw7ld/vbHwzI9eNEQDgWsK2/msecMtpaCaFQj5iY8v5gfCsCg9/RZxieoCd+0w6Qc6AhHMiWh1OCEWDQxi0t5a5qJ0F/bGvh9mNiUqZ74yddbl+qTTHDrPwLgQy9GIr9o5OIbSpn7wuf9Ep4=
before_install:
- if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]] ; then openssl
  aes-256-cbc -K $encrypted_ea9b11edcea7_key -iv $encrypted_ea9b11edcea7_iv -in deploy_key.enc
  -out deploy_key -d; fi
- echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/sshconfig
