language: java
sudo: false
jdk:
- oraclejdk8
notifications:
  slack:
    rooms:
    - gtas:G1lDbK5rR8cNBEhlszZNGDnL#general
    on_success: change
    on_failure: always
  email:
    recipients:
    - david.j.ertel@cbp.dhs.gov
    - maneesh.lekkala@gmail.com
    - taylorjwdev@gmail.com
    - jtangfed@gmail.com
    - vempatisvr@gmail.com
    - mikecope@gmail.com
    on_success: change
    on_failure: always
before_script:
- cd gtas-parent
- sed -i 's/admin/'"$DB_PASS"'/' gtas-commons/src/main/resources/hibernate.properties
- sed -i 's/localhost/'"$DB_HOST"'/' gtas-commons/src/main/resources/hibernate.properties
- sed -i 's%message.dir.origin=.*$%message.dir.origin=/usr/share/gtas/dev/in%' gtas-job-scheduler-war/src/main/resources/jobScheduler.properties
- sed -i 's%message.dir.processed=.*$%message.dir.processed=/usr/share/gtas/dev/out%'
  gtas-job-scheduler-war/src/main/resources/jobScheduler.properties
script: mvn clean package
after_success:
- cd ..
- chmod 600 deploy_key
- mv deploy_key ~/.ssh/id_rsa
- scp gtas-parent/gtas-webapp/target/gtas.war gtas-parent/gtas-job-scheduler-war/target/gtas-job-scheduler.war
  $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
env:
  global:
  - secure: z5qI+51OvU7RtSasihkGSaOgKP29YEv0+kpDTsjzilgKT8I4xeV2/uk5w66vB7IH+A+AQkTwlmuv4HWw/nDE4iqNmHx47OXAzIbAKLG7LFqlNlXqSdKyUN5SPZKW9i52x3kxhzzZIVJhaLoxGjduGRzNBq7ayl2pziP9v1kZTNzb/RHMmErG5eh8bBIO5dcqzAHJTkTQ6ircCUdQhwxo0Xk0ExvJFa8Xnf78zCpwx6Ek0eFGljDDeE0Hvum7HNxjGWxo+Mmk43XHKW9HpQmlUeoB/JGxaz3hH8Eb4iJqPNFGfNq6kcQME5VVJz230OMxyh6ptHMay33/IV10CYBBdYtky+tW9Pba0JSqvFTFN5hu+5LHHe9rMW3QfkSAsUrRgy4lm4ptDFN+DKYEzyR40T4F9tEu+DqZa/VX2aIOiWGJO+SpMyOTtQPmzBAh+jeFkcxKgppEFtOPQJSrPsJhCmJQmuDClajVQPGtJ/4p6e9Mu2zEYRrwIKN20c9nb7HKQ1NqNMTxteL7s/SkzRPKkTlnw7V42xdVpZ1y1wBgo28Vusb7Ds2WACvCvmCutxdjDLaLhW5nrPucJNtiu4cft+DJiQeodY//9mTGd/ujq+4+63lYL8K8dWHtdyHhJ7jj/j0oF3N29iRerszCrRVb8q9EknbcWqEgjehcP0xv0Wc=
  - secure: 4bqRPhawU4NRbxFP+v7pgzEeh1hfJ8jNMfgBeI5+RtxF8+phlu9zP7exFxvHC8tJGv45ibSdqVkDQF6b4RPUcOdhUzmkVQZ/ojn92YgsznTmrikztVW+IhR0PHi5mYEOIGmvmmp89IDawgUGzvlrhJrw7VydoymfYdYymgCfT2hMF5YZPHEvU33R2Clnuwb7cBLKV1sarsclKlOdBRDHurOr3QrUD/HzS/HRVudOkFbftSI/ogsKpnCRlS7l5BJ72hECrA5XGzKOXIhBpQqfOjtbRD6UMAHcPlaFoHrQ2Nrzv9tx8cMyueLcYO3GHCmaL8jku4uzLQWmMnhKyQOGIRv3v4mcQkWnQK22cW/lirYhJy+8JhhofG/r+2wKAo6vSPE5Fm/mrElTQESMpFv3CILXuI+0OjHTh5PkcJOUDr1phJ/oE9fNOk3LxWx2ty1zSplOEkD2l0PkEizMHVXtiB4rbwgPsGPg+pVGnUMq/wX19AkKxGTqsH07UdPD4ZP+jzZ0fme0eQhC7niixeVfnWcSAYeoKIHiKZfIUhQiT/4tbh9yXypWDlP1iCrLi+CqP2tem3QHGK2UQ/QR5wP8W0LeAAq3FxvjCM136SEp+RsbTkWRobByMUJFN/gQhqPM7/yc1/lUFZtjFSNT7opdfZQgjfyhw+y8USbTmOl+2xI=
  - secure: RA500kpV1LGhBt5zQKpt5wsNZuKe4kipz7ZdtYVO3F5UyR+FaQTqI/0DnRTqEUSxdb9Pov4MkYsVAVw8pAuIWTci6CscOslz2at2J26ybQo3fsgp3YP8oc06l4y6dy65AZeT53zlSHCdmSOv0PkSbU7mXUqztbMZXurqwtrSVeMYeQU+63VGf2Y9rC9Rc/6qLbm0xlj9m6eyK8pCeyZNLjoqZD+K3PhAKFE0+9aCQuBxQpopy0mU6Vg+vwbjYHaFja2wgE6zi5nRxnoQ1zxk0Qtfav/3s7BQ4Wdi6uQ33Jdn/GFry2tZCn+l+SwYH75VERjIiTy5q4tOKDcz4d3WQwvoLHhz8P4KDvwZsClTGONIqCuEaL6i1Ahy7nNNsxsdMx3vNfBilV7nqMJ1gLOr9Wq0hAXr7ZDEiCX2U9WJogHxaLfmouoYfC7F2MfibySNhLmo6JKx8+eZxhyf3SrBfE2pg96BbpsT38Bd4RVR5fcA4Zqh7/Sf4yjaBRRcYtc9EvU93qDq9Me0bdFr3/Z13q1qIuHWtF6aqTEZyShio6gCVYkBgx/wT66nkB5OTdWLu5/gCSULo+Uo6huVnCnxcUcmc1K697MGg3pxHtQXHd34VvNsoRMewnaohGHjJeQYUJjaA6OVPnoh0gFcYourBbkCUVAoPiLP0xaCe61r6F0=
  - secure: gipF+Z0XVLlWI4s9YOBH9YqoMr45uqiS8qF2FVKo+v7SeyhXuguGquxWnMoF8i5N38HkUFhF8arFBltJmhBNNFhXIhxZjbOoMdxebthAdux5TpiKS0LmjRZRb1nO1ff+fsGMyiEHzpY0rdQFRNx8obkbz83KR9TERI1UOvfQjIodeczLvt80lz5mWCDLqL6BaKU2XAALmCFUD8VbFfdcZkC3lH74BF7vWjjr8XhME7JeJcWWnpxwbOUwQ4mFxhxEtf9jqPsyWzjxLTkLFt5Gprk8HRkEqprMQr+l98PkHH11/3V/cTafIFK54GQ9VwUl/WEvZVrpvBdmNhkW67Ndcc7JbilU+QY8gLDdjPlv4Ma/u062v8G/xJB2JjyG7tzLGj7+vDB8j9l/yj2ZYtSCKGKLuetTNXVYhxLMfwnnAIH5QF1BYS6nd4N8Qn3ZPRP3S+TlCYR18d6BvVrWe1BcNe+wqS0hldSZQ7FGVMpPb1fBN0nCiMJOYy5aGHanJaMRQOcUnOJsqSUClIqB7uqYf5r6tVRMruKJH+wfXkT+aAmST1Qa4YS8+UU9w3Od0zTCWe34GhxrilFdS4omTvIrpc7aYqELQeMV/hL+hfxw/qPC0518Vj9wiHHNMNQ+Xb98eD8ebU0dog7nQ8/9dafN4gYdXUA3YrD+T7XkU1m6mAw=
  - secure: aS88ht+GoJVegVp2d0xz9rAuXPYxW/FQC7nZqe/ZntONZz7bj1Rp9dJnNzSvQd0atPUCsTARXXUaikkLkgou9EHqMKrwji6AJCGQi5THeOwQEWemBG+YZjuGkmAa7EFlVHhL05MWVsGi3eHEhgtHL1+GX1RduTaqViuWgUWrEabfWknVozvhcTq4fG13UVvQJAIEgEpAnzJ/eYb+uP8klhqLkNaApkAeA0SzSS1ETvCbwjOIwTpAiP/1dSF0OsrB1ZMLXFEfPbcbJ6J0Ek7le9ZZdCC2qN1bJHvdlCD3aiNupFy2V12FqpCDJt9J6ev1r3meo6n4nXTfvVORgvY6+zDPEOEzv+zNcDsvv9RIeU83PhMF6OW8NbdAZv6wSyj1YaWfTbHJb5cFbjtoHe5++cSjwx5sepry8ZG/d53rzHaAdGGvjPxNslw2AGXrGUxCSDqCml0hmEgFt+DZHyG4dOpPbnzxAm6EKC0OD9q+9nVTlqKyjYmYO1k0AtQiumVwKX5wFg6IAbHJ6ora+VVvnajX0qNhRlQEnHQFT2ihttsIb0UObeuICFn7X7aVtA5eUe9Ja/diw1acBJmXC+58/4X662lxQuqLczk64OMNUXuBACY1e1brHJunrv18ge3mj6/oVgQgXWwMCDOU7hLkbuzQIZCcFaVhgokQRf5csoI=
before_install:
- if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]] ; then openssl
  aes-256-cbc -K $encrypted_ea9b11edcea7_key -iv $encrypted_ea9b11edcea7_iv -in deploy_key.enc
  -out deploy_key -d; fi
- echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
