version: '3.7'
services:
  webapp:
    container_name: webapp
    build: './gtas-parent'
    ports:
      - 8080:8080
    environment: 
      - DB_HOST=mariadb
    networks:
      - GTAS_webapp-network
      - GTAS_logstash-network
    restart: unless-stopped
    secrets:
     - mysql_webapp_user
     - mysql_webapp_password
    volumes:
      - m2:/root/.m2
    depends_on: 
      - mariadb

  mariadb:
    build:
      context: './gtas-parent'
      dockerfile: 'Dockerfile-mariadb'
    container_name: mariadb
    environment:
      MYSQL_DATABASE: gtas
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    healthcheck:
      test: "mysql --user=$$(cat /run/secrets/mysql_healthcheck_user) --password=$$(cat /run/secrets/mysql_healthcheck_password) --execute \"SHOW DATABASES;\")"
      interval: 5s
      retries: 36
    secrets:
     - mysql_etl_user
     - mysql_etl_password
     - mysql_processor_user
     - mysql_processor_password
     - mysql_webapp_user
     - mysql_webapp_password
     - mysql_healthcheck_user
     - mysql_healthcheck_password
     - mysql_root_password
    ports:
      - 3306:3306
    networks:
      - GTAS_webapp-network
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
secrets:
  mysql_etl_user:
    file: ./gtas-parent/gtas-commons/mariadb/mysql_etl_user.txt
  mysql_etl_password:
    file: ./gtas-parent/gtas-commons/mariadb/mysql_etl_password.txt
  mysql_healthcheck_user:
    file: ./gtas-parent/gtas-commons/mariadb/mysql_healthcheck_user.txt
  mysql_healthcheck_password:
    file: ./gtas-parent/gtas-commons/mariadb/mysql_healthcheck_password.txt
  mysql_processor_user:
    file: ./gtas-parent/gtas-commons/mariadb/mysql_processor_user.txt
  mysql_processor_password:
    file: ./gtas-parent/gtas-commons/mariadb/mysql_processor_password.txt
  mysql_webapp_user:
    file: ./gtas-parent/gtas-commons/mariadb/mysql_webapp_user.txt
  mysql_webapp_password:
    file: ./gtas-parent/gtas-commons/mariadb/mysql_webapp_password.txt
  mysql_root_password:
    file: ./gtas-parent/gtas-commons/mariadb/mysql_root_password.txt
volumes:
  db-data:
  m2:
networks:
  GTAS_logstash-network:
    driver: "bridge"
  GTAS_webapp-network:
    driver: "bridge"