version: '3.7'
services:
  webapp:
    build: './gtas-parent/gtas-webapp'
    ports:
      - 8080:8080
    networks:
      - gtas_network
    restart: unless-stopped
    depends_on:
      - builder
    volumes:
      - m2:/root/.m2
  builder:
    build: './builder'
    networks:
      - gtas_network
    depends_on:
      - mariadb
    volumes:
       - gtas-parent:/gtas-parent
       - m2:/root/.m2
  mariadb:
    build: './mariadb'
    environment:
      MYSQL_DATABASE: gtas
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
     - mysql_root_password
    ports:
      - 3306:3306
    networks:
      - gtas_network
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
secrets:
  mysql_root_password:
    file: ./mariadb/mysql_root_password.txt
  mysql_webapp_password:
    file: ./mariadb/mysql_webapp_password.txt
  mysql_etl_password:
    file: ./mariadb/mysql_etl_password.txt
  mysql_processor_password:
    file: ./mariadb/mysql_processor_password.txt
volumes:
  gtas-parent:
    driver_opts:
      type: none
      device: ${PWD}/gtas-parent
      o: bind
  db-data:
  m2:
networks:
  gtas_network:
    driver: "bridge"