version: "3.4"

services:
  
  mariahost:
    image: mariadb
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: gtas
    ports:
      - "3306:3306"
    container_name: mariahost
    networks: 
      - gtas_default
  
  
networks:
  gtas_default:
