version: "3.7"

services:

  kibana:
    container_name: kibana
    build:
      context: ./gtas-parent/scripts/elastic
      dockerfile: install/docker/kibana/Dockerfile
    environment:
      ELASTICSEARCH_HOST: 'elasticsearch'
    ports:
      - 5601:5601
    restart: always
    volumes:
      - '$PWD/gtas-parent/scripts/elastic:/config/kibana'
    networks: 
      - GTAS_elastic-network
      - GTAS_webapp-network
    depends_on:
      - elasticsearch
    # secrets:
    #  - kibana_keystore

  elasticsearch:
    container_name: elasticsearch
    build:
      context: ./gtas-parent/scripts/elastic
      dockerfile: install/docker/elasticsearch/Dockerfile
    ports:
      - 9300:9300
      - 9200:9200
    restart: always
    volumes: 
      - "es-data:/usr/share/elasticsearch/data"
    networks: 
      - GTAS_elastic-network
    # secrets:
    #   - elastic_keystore

  logstash:
    container_name: logstash
    build:
      context: ./gtas-parent/scripts/elastic
      dockerfile: ./install/docker/logstash/Dockerfile
    environment: 
      MARIADB_HOST: 'mariadb'
      ELASTIC_HOST: 'elasticsearch'
    restart: always
    networks:
      - GTAS_elastic-network
      - GTAS_logstash-network
    volumes:
      - "logstash_keystore:/usr/share/logstash/config/"
    depends_on:
      - elasticsearch

  elk-setup:
    container_name: elk-setup
    build:
      context: ./gtas-parent/scripts/elastic
      dockerfile: ./install/docker/elk-setup/Dockerfile
    environment:
      KIBANA_HOST: 'kibana'
    tty:
      false
    volumes:
      - "logstash_keystore:/logstash-keystore"
      - "kibana_keystore:/kibana-keystore"
      - "elasticsearch_keystore:/elasticsearch-keystore"
    secrets:
      - logstash_keystore_password
      - mysql_logstash_user
      - mysql_logstash_password
      - elastic_user
      - elastic_password
      - elasticsearch_kibana_user
      - elasticsearch_kibana_password
    networks:
      - GTAS_elastic-network


secrets:
  logstash_keystore_password:
    file: ./gtas-parent/gtas-commons/secrets/logstash_keystore_password.txt
  mysql_logstash_user:
    file: ./gtas-parent/gtas-commons/secrets/mysql_logstash_user.txt
  mysql_logstash_password:
    file: ./gtas-parent/gtas-commons/secrets/mysql_logstash_password.txt
  elastic_user:
    file: ./gtas-parent/gtas-commons/secrets/elastic_user.txt
  elastic_password:
    file: ./gtas-parent/gtas-commons/secrets/elastic_password.txt
  elasticsearch_kibana_user:
    file: ./gtas-parent/gtas-commons/secrets/elasticsearch_kibana_user.txt
  elasticsearch_kibana_password:
    file: ./gtas-parent/gtas-commons/secrets/elasticsearch_kibana_password.txt
  # elastic_keystore:
  #   file: ./gtas-parent/gtas-commons/secrets/elastic.keystore
  # kibana_keystore:
  #   file: ./gtas-parent/gtas-commons/secrets/kibana.keystore

volumes:
  logstash_keystore:
  kibana_keystore:
  elasticsearch_keystore:
  es-data:

networks:
  GTAS_elastic-network:
    driver: "bridge"
  GTAS_logstash-network:
    driver: "bridge"
  GTAS_webapp-network:
    driver: "bridge"