version: "3"

services:
  redis:
    image: redis:latest
    container_name: redis
    networks: 
      - gtas_default

  activemq:
    image: rmohr/activemq
    container_name: activemq
    networks: 
      - gtas_default

  mariahost:
    image: sanandreas/gtas_mariadb:v3
    container_name: mariahost
    networks: 
      - gtas_default
  
  tomcatgtas:
    image: sanandreas/gtas_tomcat:v3
    container_name: tomcat
    networks: 
      - gtas_default
    ports: 
      - 8080:8080
    volumes:
      - //C/db/input:/usr/local/input:rw
      - //C/db/output:/usr/local/output:rw

networks:
  gtas_default:
