instances:  
  - name: 'gtas-master'
    dns:  [ 'master.elastic.local', 'localhost' ]
  - name: 'kibana'
    dns:  [ 'kibana.local', 'localhost']
  - name: 'logstash'
    dns:  [ 'logstash.local', 'localhost' ]