version: "3.4"

services:
  neo4j:
    build:
      context: .
      dockerfile: ./neo4j.Dockerfile
    container_name: neo4j
    ports:
      - 7474:7474   
      - 7687:7687
    networks: 
    - gtas_default
  etl-job:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: etl-job
    networks: 
    - gtas_default
    depends_on: 
      - neo4j
      - mariahost

  mariahost:
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "3306:3306"
    container_name: mariahost
    command: [
            '--wait_timeout=28800',
        ]
    networks: 
      - gtas_default

networks:
  gtas_default:
    driver: "bridge"
  
  